### ISSUE TITLE
How to do Post request?

### ISSUE THREAD

**Issue by Hp-Ro** [gsemac/Gsemac.Net.Cloudflare#6]
idk what what am doin but thats my code : 
```
            var requestString = "{\"isInstagramInAppBrowser\":false,\"isSnapchatInAppBrowser\":false,\"isSenderRevealed\":false,\"tell\":\"" + GetLetter() + "\",\"userId\":" + id + ",\"limit\":25}";

            using (ServiceProvider serviceProvider = CreateServiceProvider())
            {
                IWebClientFactory webClientFactory = serviceProvider.GetRequiredService<IWebClientFactory>();
                using (IWebClient webClient = webClientFactory.Create())
                {
                    var json = webClient.UploadData("https://api.tellonym.me/tells/new","POST", Encoding.ASCII.GetBytes(requestString));
                    MessageBox.Show(json.ToString());
                }
            }
```

**Comment by gsemac** [comment]
Try the solution given here: https://github.com/gsemac/Gsemac.Net.Cloudflare/issues/1#issuecomment-1046448497

Basically, you have to decorate the request with `LazyUploadHttpWebRequestDecorator` so the POST data can be re-read when the request fails.

**Comment by Hp-Ro** [comment]
i have solve it but now am getting 
![image](https://github.com/gsemac/Gsemac.Net.Cloudflare/assets/65039444/6b0067f6-63d2-4aac-a59a-f7d89c59dc15)

**Comment by gsemac** [comment]
I believe this response is coming from the API you're consuming, not FlareSolverr.
