### ISSUE TITLE
Cookies and Set-Cookie header management

### ISSUE THREAD

**Issue by McIvanX** [gsemac/Gsemac.Net.Cloudflare#7]
Hey, i have been messing around for a bit but still i dont find any way to get both, cloudflare cookies and the cookies that the website sends when going in it.

Is there any way to do this?

**Comment by McIvanX** [comment]
By the way, i keep getting error 403 when trying to do requests

**Comment by gsemac** [comment]
Are you using the FlareSolverr challenge handler, and is FlareSolverr running? It's the only one that works right now.

If you want to access the response cookies directly, you could add a custom delegating handler to read them from the response object. Something like this:

```csharp
class MyCustomHandler :
    HttpWebRequestHandler {

    protected override IHttpWebResponse Send(IHttpWebRequest request, CancellationToken cancellationToken) {

        var res = base.Send(request, cancellationToken);
        // do whatever you want with the cookies here
        return res;

    }

}

private static WebRequestHandler CreateWebRequestHandler(IServiceProvider serviceProvider) {

    WebRequestHandler innerHandler = new WebRequestHandler();

    return WebClientFactory.CreatePipeline(innerHandler, new DelegatingWebRequestHandler[] {
        ActivatorUtilities.CreateInstance<FlareSolverrChallengeHandler>(serviceProvider),
        new MyCustomHandler(),
    });

}

static ServiceProvider CreateServiceProvider() {

    return new ServiceCollection()
        .AddSingleton<ILogger, ConsoleLogger>()
        .AddSingleton<IWebClientFactory, WebClientFactory>()
        .AddSingleton<IFlareSolverrService, FlareSolverrService>()
        .AddSingleton(CreateWebRequestHandler)
        .BuildServiceProvider();

}

static void Main(string[] args) {

    using (ServiceProvider serviceProvider = CreateServiceProvider()) {

        IWebClientFactory webClientFactory = serviceProvider.GetRequiredService<IWebClientFactory>();

        using (IWebClient webClient = webClientFactory.Create()) 
            Console.WriteLine(webClient.DownloadString("https://example.com/"));

    }

}
```

**Comment by McIvanX** [comment]
Testing it, also, the 403 have been getting isnt from here, its from a request that i do using Leaf.xNet right below

**Comment by McIvanX** [comment]
Ive made some changes, and i added this yet no cookie prints

		foreach (Cookie cookie in request.CookieContainer.GetCookies(request.GetResponse().ResponseUri))
		{
            Console.WriteLine(cookie.Name + " -> " + cookie.Value);
		}

**Comment by McIvanX** [comment]
By the way, i still doing have clear how to do POST requests, because it asks me for a decorator, i know about issue number one but i dont know to implement a "IHttpWebRequestFactory" when in my program its a "IWebClientFactory"

**Comment by McIvanX** [comment]
Nevermind about that one, im sleepy, i added this line in CreateServiceProvider:

				.AddSingleton<IHttpWebRequestFactory, CustomHttpWebRequestFactory>()

**Comment by gsemac** [comment]
> Ive made some changes, and i added this yet no cookie prints

All I can think of is that the cookies may be assigned to a different domain than what `ResponseUri` returns, so `GetCookies` isn't returning anything. You could use the debugger to inspect them, or depending on the version of .NET you're using, you might be able to use the `GetAllCookies` method on the `CookieContainer` to access them.

> Testing it, also, the 403 have been getting isnt from here, its from a request that i do using Leaf.xNet right below

Make sure that your request uses the same user agent string as FlareSolverr, because if it doesn't match, the cookies won't work.
